### ISSUE TITLE
Appendix A「集約とイベントソーシング」

### ISSUE THREAD

**Issue by hiromoon** [hiromoon/PolarBearClassroom#18]
> イベントソーシングを使うと、集約全体の状態を、作成時以降に発生したイベントのシーケンスとして表せる。

* 集約のイベントストリームは、イベントストアに永続する
* イベントストリームは、集約のルートエンティティの識別子で区別する

A+ES(Aggregates and Event Sourcing)
* メリット
  * インスタンスに変更が加わった理由を失わないように保証できる。
  * 追記しかできないのでパフォーマンスが良くなる
  * データのレプリケーションも可能
  * イベント中心の設計にするとORMのインピーダンスミスマッチを回避でき、設計に注力できる。
* デメリット
  * イベントを定義するために業務ドメインに関する深い知識が必要になる
  * 何らかの形でCQRSが必要になる

**Comment by shirosuke** [comment]
とりあえずA6までやった範囲で。

## 導入部
* 集約とイベントソーシング（以下、A+ES）の導入は、あらゆる面でメリットがある
  * 集約に対する変更履歴を保持することで、以下の様に活用できる。
    * ビジネスインテジェンス、分析への活用
    * 監査証跡
    * 障害時のデバッグ
    * **(?)パフォーマンスが良くなる**
        * 従来の方法（ステートソーシング）に対して言ってる?  
* もちろんデメリットもある
  * 導入する為には、深い業務知識、それに基づくドメインモデリングは必須。
  * 技術的にも、導入の敷居が高い。
    * ツールそろってない、知識体系まとまってない（本書執筆時点だから今は状況違うかも）
    * CQRSのスキル前提

## A.1　アプリケーションサービスの内部構造
* どの登場人物があって、どのような処理の流れになるかは図A-2通り。
* 集約のコンストラクタに、イベントストリームから取得したイベント群を渡して、初期化する。
  * `Mutate`メソッドを経由し、各イベントの型にマッチする`When`メソッドを実行し、集約を復元する。
* 復元した集約に対して、状態を変更する場合は、`Apply`メソッドを経由する。`Apply`メソッドは、集約が保持している`Changes`コレクションに、状態変更のイベントを追加し、その後`Mutate`メソッドを実行し、集約の状態を変更する。
* 集約の状態変更が完了したら、`Changes`コレクションをイベントストアに永続化する。
  * 並行処理における衝突は、イベントストリームが持つバージョン変数を用いて制御する。
* イベントストアの耐障害性を高める為に、イベントストアをクローンする線略がある。
  * クローンのイベントストアへ、イベントの複製が成功してはじめてイベントの保存が完了したとみなす方式（ライトスルー戦略）
  * 別スレッドを使って、クローンにイベントを複製する（ライトビハインド戦略）
      * パフォーマンスはこっちの方が良さそうだが、マスターとクローンが同期していない状態がありえることも想定した対応が必要になる。

## A.2　コマンドハンドラ
* コマンド + コマンドハンドラによるアプリケーションのタスク管理
* メソッド名とそのパラメータをコマンドとしてシリアライズし、メッセージキュー経由で外部に送信できる。
* 送信されたコマンドは、コマンドハンドラが受け取る。このコマンドハンドラは、責務的にアプリケーションサービスのメソッドを置き換えることができるので、クライアント-アプリケーションサービス間を切り離すことができる。
  * 負荷分散に強くなり、**(?)競合コンシューマパターンも使え**、**(?)システムのパーティショニングにも対応できる（らしい）**。
  * 時間的な分離が実現できる。アプリケーションサービスがダウンしてても、コマンドはメッセージキューにストックされ、アプリケーションサービスが復旧した際に、コマンドを実行する。
  * コマンドのディスパッチ時に、別のアスペクトを仕込めることもメリット。
    * 監査、ログ出力、認証、バリデーション
  * 各種の障害への対応や異常系の処理も、1箇所でまとめて実施できる。

## A.3 ラムダ構文
* ラムダ式をサポートする言語なら、A+ESの実装に必要なコード量をもっと少なくできるよ。

## A.4 並行性制御
* イベントストアへの更新が競合した場合の再送処理に関するパターン。
  * 専用の例外を投げ、すぐに再試行する。
  * 再試行が難しい場合、競合解消を試みる。
    *  衝突検出用の`ConflictsWith`を各集約のルートエンティティごとに定義するのが一般的。
    * 「同じ型のイベントは、常にお互いを衝突する。しかし、異なる型のイベントは決して衝突しない」というシンプルな競合ルールの場合は、イベント型同士の比較によって競合を解消できる。
      * **(?)実際の業務で利用するようなシステムで、そんなシンプルなパターンがあり得る。。?**

## A.5 構造上の束縛から解放されたA+ES
* A+ESを利用する最大の現実的なメリットは、集約の永続化がシンプルになり、多用途に利用できること。
* 整合生を強く担保しているストレージであれば、イベントストリームの永続化に利用できる。
* **(?) 「変更のリスクは少なくなるし、開発者にも負担がかかりにくくなる。」に違和感。集約の内部構造の変更に対しては強いかもしれないけど、大規模なリファクタリング（ex. 新しい集約ができて、古い集約が消える様なパターン）の時、本当にそう言えるのか。**
  * 上記のパターンの時、データ移行にどのように対応するのか、イメージが湧かない。。

## A.6 パフォーマンス
* 履歴したイベントがすごい量になると、集約の復元にパフォーマンス上の問題が出てくる。
    * イベントストリームをキャッシュする。キャッシュと、イベントストアの最新の状態を比較し、その差分のイベントを取り込むことでコストを削減する。
* スナップショットを利用する。集約のインスタンスを読込む時、最新のスナップショットを取得し、そこから追加されたイベントを再生する。
    * スナップショットには、ストリームのバージョンを保持させる。
    * スナップショットから、状態を復元する為のメソッド`ReplayEvents`を利用する。
        *  `Apply`をそのまま利用しないように
* スナップショットの生成＆永続化はバックグラウンドプロセスに移譲できる。周期はパフォーマンス要件に依る。

**Comment by Shusaku-Sahashi** [comment]
# イベントソーシング
* 集約の全体の状態を発生時以降にイベントのシーケンスとして表せる。
* 集約のイベントストリームは個々のストリームを区別する為に、ルートエンティティの識別子を使用してイベントストアを永続する。
  * そもそも使用状況は？
    * 日中状態だけをプールしておいて、夜間にバッチ処理を実施してデータを更新する場合
    * イベントのトレースを残しておく場合
    * など？

## A.1 アプリケーションの内部構造
* Mutate()メソッドで復元と保存を実施する。
  * Change.add()にある場合は、イベントストアに永続化を実施する。
  * **（疑問）**復元時も同じメソッドなのはいいのか？
* A + ESでは実装クラスと状態を管理するクラスを分割し、Apply()メソッドがその橋渡しをする。これにより、Applyメソッドを使用しない場合は状態の変更を許さない。
* ライトスルー方式と代とビハインド方式がある。
  * ライトスルーは同期的
  * ビハインド方式は結果整合性的？

* 書籍に記載されている①〜⑧の手順を使用して過去のイベント発生時からの処理を復元可能。
  * **（疑問）**これって、過去のイベント発生時から再度ビジネス操作をしているが、どんな状況？

## A.2 コマンドハンドラ
* コマンドとコマンドハンドラを使用してタスク管理を実施する。
* 利点
  * クライアントをアプリケーションサービスから切り離せる。
    * 負分散に有利
    * 競合コンシューマパターンが使える。
    * システムのパーティショリングに対応できる。
* クライアント側からはコマンドのみを指定してメッセージキューに投げる。メッシージキューから各サーバーのメソッドを呼び出す。この時処理はコマンドで決まるのでディスパッチで呼び分けを行う。

* 必要に応じてアスペクトを埋め込める。
  * ログ出力、認証、バリデーションなど

## A.3 ラムダ構文
deligate以上！！
* 他の言語でも関数を変数に入れられれば同じ感じでできる。

## A.4 並行性制御
* 衝突が起きたことを例外として処理、例外もとの方は再度衝突が起きたイベントまで読み込んで、自分の処理部分の更新をかける。　
  * この時、新規イベントとして登録される。
* 同タイミングでイベントストアに登録されたものに関しては、イベントの衝突確認を行う。
* Simpleな実装が書籍には示されている。（`ConflictsWith()`）
  * これを使用するにはイベントの粒度がかなり小さくないといけない気がする。
    * **（疑問）**アグリゲートルートで変更する単位を最小限におけというルールが利いてくる？

## A.5 パフォーマンス
* 一つのストリームに大量のイベントが入っている場合パフォーマンスの問題がある。
  * イベントストリームの１単位って何で定義されるの？
* これを解決する方法として集約のある時点をスナップショットとして保存しておく方法がある。
*　イベントが一定数溜まったら、スナップショットを作成するという処理をバックスレッドに任せることも可能。
* **（意見）**データ移行時の一つの案として、スナップショットがあるかも。。（データ移行以後のデータでスナップショットを取っておく。）
