### ISSUE TITLE
第一部 ドメインモデルを機能させる

### ISSUE THREAD

**Issue by hiromoon** [hiromoon/PolarBearClassroom#24]

**Comment by hiromoon** [comment]
### モデル
* ドメインエキスパートのもつ知識を厳密に構成し、抽象化されたもの
* ドメインモデルを読み解くことによって、コードを解釈することができる
* モデルと実装が密接に結びついていると、開発チームはモデルを使って会話ができる

### ソフトウェアの核心
* ソフトウェアは、それを使ってユーザが問題を解決できることに意味がある
* その出来自体は主にモデリングによって解決ができる
* 技術者の興味は複雑性に向くことが多いが、複雑性を技術ではなくモデリング対応することができる
  - 多くの場合、技術的に正しいことと課題解決の核心が異なるからだ

**Comment by shirosuke** [comment]
読んだ。疑問点とかは無いので次へ。
