### ISSUE TITLE
第一章 知識を噛み砕く

### ISSUE THREAD

**Issue by hiromoon** [hiromoon/PolarBearClassroom#25]

**Comment by hiromoon** [comment]
### 効果的なモデリングの要素
* モデルと実装を結びつける
  - 結びつけることによってドメインエキスパートと開発者のコミュニケーションがモデルを元にできるようになる
  - 次第にモデルをもとに言語が洗練されていく
* モデルは単なるスキーマではなく、振る舞いやルールを持つ知識として扱う
* 知識を付け足すだけでなく、不要な概念が含まれている場合には取り除いて新プリにしていく
* モデルが使用可能なものかをかならず検証する

### 知識の噛み砕き
* 従来は、ビジネスエキスパート -> アナリスト -> デベロッパ と知識が渡されて開発される
* この方法では、デベロッパからビジネスエキスパート、ビジネスエキスパートからデベロッパへのフィードバックがされないため、お互いに成長しない
* ビジネスエキスパートの知識を噛み砕いて共有することで、モデルがより洗練されていく

### 継続的学習
* 誰でもプロジェクト参加時はドメインの初心者
* 継続的に学習を重ねることで次第にドメインエキスパートへ近づいていく

### 知識豊富な設計
* ドメインエキスパートは自分の知識がいかに複雑なのかを理解していないことが多い
  - 人間は意識せずとも調整して実行できるが、機械はそうはいかない
* 知識をきちんと整理してモデルに持たせることが必要
* きちんと知識をモデリングすることで、ドメインエキスパートにコードを読ませることでさえ可能にする

### 深いモデル
* モデリングの結果に、ビジネスエキスパートが満足しないことがある
  - ビジネスエキスパートなりのビジネスの見方がある
* ビジネスエキスパートの見方を取り込んでモデルを洗練させることで、劇的にモデルは進化していく

**Comment by shirosuke** [comment]
まとめありがとう。こっちも読み終わった。
疑問点とか特に無いので、感想書くわ。

メリットは十分すぎるほど伝わったが、DDDを導入・回していくまでの敷居は超高いように感じた。
* ビジネスエキスパートにDDDの方法論の有用性を理解してもらい、開発者と知識を共有する機会　をとってもらうこと
* 開発者が技術的な側面だけでなく、ドメインについても継続的に学習していくという姿勢
* 上記を継続的に続けていき、モデル及びチームのDDDのスキルを高めていくこと
